[docker_server]
docker_soft ansible_host=localhost ansible_connection=local
[harbor_server]
harbor_soft ansible_host=localhost ansible_connection=local
[vault_server]
vault_soft ansible_host=localhost ansible_connection=local
[kubernetes_server]
kubernetes_soft ansible_host=localhost ansible_connection=local


